when user is not logged in and does not have a googleid, do not try to look it up in the database
should fix this error:

TypeError: Cannot read properties of undefined (reading 'googleid')
    at /home/manjaro/weblab23/ShadowMe/server/api.js:40:59